import StaticPageLayout from '../../components/StaticPageLayout';

export const metadata = {
  title: 'Terms of Service | ShipLog',
  description: 'ShipLog Terms of Service - the rules and guidelines for using our service.',
};

export default function TermsPage() {
  return (
    <StaticPageLayout>
      <article className="prose prose-navy max-w-none">
        <h1 className="text-3xl font-bold text-navy-900 mb-2">Terms of Service</h1>
        <p className="text-navy-500 mb-8">Last updated: February 2026</p>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-navy-900 mb-4">1. Acceptance of Terms</h2>
          <p className="text-navy-600">
            By accessing or using ShipLog (&quot;the Service&quot;), you agree to be bound by these Terms of Service. 
            If you do not agree to these terms, please do not use the Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-navy-900 mb-4">2. Description of Service</h2>
          <p className="text-navy-600">
            ShipLog is a software-as-a-service platform that generates AI-powered release notes from your 
            GitHub repositories. The Service analyzes your commits, pull requests, and releases to create 
            audience-appropriate documentation.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-navy-900 mb-4">3. Account Terms</h2>
          <ul className="list-disc pl-6 text-navy-600 space-y-2">
            <li>You must provide accurate information when creating an account.</li>
            <li>You are responsible for maintaining the security of your account.</li>
            <li>You must be at least 18 years old to use this Service.</li>
            <li>One person or entity may not maintain multiple free accounts.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-navy-900 mb-4">4. Payment Terms</h2>
          <ul className="list-disc pl-6 text-navy-600 space-y-2">
            <li>Paid plans are billed monthly or annually in advance.</li>
            <li>All fees are non-refundable unless required by law.</li>
            <li>You authorize us to charge your payment method for recurring fees.</li>
            <li>Prices may change with 30 days&apos; notice.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-navy-900 mb-4">5. Acceptable Use</h2>
          <p className="text-navy-600 mb-4">You agree not to:</p>
          <ul className="list-disc pl-6 text-navy-600 space-y-2">
            <li>Use the Service for any illegal purpose.</li>
            <li>Attempt to gain unauthorized access to the Service.</li>
            <li>Interfere with or disrupt the Service.</li>
            <li>Use the Service to generate harmful, abusive, or misleading content.</li>
            <li>Resell access to the Service without authorization.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-navy-900 mb-4">6. Intellectual Property</h2>
          <p className="text-navy-600">
            You retain ownership of your code and content. The release notes generated by ShipLog are 
            yours to use as you see fit. ShipLog retains ownership of the Service, including all software, 
            designs, and documentation.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-navy-900 mb-4">7. Limitation of Liability</h2>
          <p className="text-navy-600">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, SHIPLOG SHALL NOT BE LIABLE FOR ANY INDIRECT, 
            INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, 
            WHETHER INCURRED DIRECTLY OR INDIRECTLY.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-navy-900 mb-4">8. Termination</h2>
          <p className="text-navy-600">
            We may terminate or suspend your account at any time for violation of these terms. 
            You may cancel your account at any time through your account settings. Upon termination, 
            your data will be deleted within 30 days.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-navy-900 mb-4">9. Changes to Terms</h2>
          <p className="text-navy-600">
            We may modify these terms at any time. We will notify you of material changes via email 
            or through the Service. Continued use after changes constitutes acceptance.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-navy-900 mb-4">10. Contact</h2>
          <p className="text-navy-600">
            Questions about these terms? Contact us at{' '}
            <a href="mailto:support@shiplog.io" className="text-teal-600 hover:underline">
              support@shiplog.io
            </a>
          </p>
        </section>
      </article>
    </StaticPageLayout>
  );
}
