import { notFound } from 'next/navigation';
import ReactMarkdown from 'react-markdown';
import Link from 'next/link';

async function getPreview(slug: string) {
  const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
  console.log(`Fetching preview from ${apiUrl}/preview/${slug}`);
  const res = await fetch(`${apiUrl}/preview/${slug}`, {
    cache: 'no-store'
  });
  if (!res.ok) return null;
  return res.json();
}

export default async function PreviewPage({ params }: { params: { slug: string } }) {
  const data = await getPreview(params.slug);
  
  if (!data) notFound();

  // Parse notes if string, handle JSON object
  let content = '';
  if (typeof data.notes === 'string') {
    try {
      const parsed = JSON.parse(data.notes);
      content = parsed.customer || parsed.developer || parsed.stakeholder || '';
    } catch {
      content = data.notes;
    }
  } else if (data.notes) {
    content = data.notes.customer || data.notes.developer || data.notes.stakeholder || '';
  }

  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-gray-100 py-6">
        <div className="max-w-3xl mx-auto px-4 flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">{data.repoOwner}/{data.repoName}</h1>
            <p className="text-sm text-gray-500">Preview Changelog</p>
          </div>
          <Link 
            href="/login" 
            className="px-4 py-2 bg-black text-white rounded-lg text-sm font-medium hover:bg-gray-800"
          >
            Claim this Changelog
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-8 prose prose-gray">
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-8 text-sm text-yellow-800">
          This is a preview generated by ShipLog AI. It has not been edited by the maintainers.
        </div>
        
        <h2>{data.title}</h2>
        <ReactMarkdown>{content}</ReactMarkdown>
      </main>
    </div>
  );
}
